# Generated by Django 2.1.3 on 2018-11-27 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoUpload',
            fields=[
                ('name', models.CharField(primary_key=True ,max_length=50)),
                ('video', models.FileField(upload_to='')),
            ],
        ),
    ]
