# Generated by Django 2.1.3 on 2018-12-24 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoUpload',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('video', models.FileField(upload_to='videos')),
            ],
        ),
    ]
