# Generated by Django 2.1.3 on 2018-11-28 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoupload',
            name='video',
            field=models.FileField(upload_to='C:\\Users\\skconan\\Desktop\\drawing_web_app\\website\\website\\media/videos/'),
        ),
    ]
